openapi: 3.0.3
info:
  title: Swagger Bunny Board - OpenAPI 3.0
  description: |-
    This is data api endpoints are serving by Bunny Board infrastructures. This documentation maybe helpful for frontend developers or data consumers.
  version: 1.0.0
servers:
  - url: https://data.bunnyboard.xyz/board
tags:
  - name: crossLending
    description: All available metrics about cross-lending protocols
    externalDocs:
      description: Find out more
      url: https://wiki.bunnyboard.xyz
paths:
  /crossLending/overall:
    get:
      tags:
        - crossLending
      summary: Get summarization of cross-lending data across all protocols
      operationId: getCrossLendingOverallData
      # parameters:
      #   - name: status
      #     in: query
      #     description: Status values that need to be considered for filter
      #     required: false
      #     explode: true
      #     schema:
      #       type: string
      #       default: available
      #       enum:
      #         - available
      #         - pending
      #         - sold
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/CrossLendingDataOverallResponse'
        '500':
          description: Server Error
components:
  schemas:
    DataValueItem:
      type: object
      properties:
        value:
          type: number
          format: uint64
          example: 10
        valueUsd:
          type: number
          format: uint64
          example: 10
        changeValue:
          type: number
          format: int64
          example: -3.2
        changeValueUsd:
          type: number
          format: int64
          example: 3.2
    DataValueItemWithoutChanges:
      type: object
      properties:
        value:
          type: number
          format: uint64
          example: 10
        valueUsd:
          type: number
          format: uint64
          example: 10
    CrossLendingDayData:
      type: object
      properties:
        timestamp:
          type: number
          format: uint64
          example: 1706745600
        totalDeposited:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
        totalBorrowed:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
        volumeDeposited:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
        volumeWithdrawn:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
        volumeBorrowed:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
        volumeRepaid:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
        feesPaidTheoretically:
          $ref: '#/components/schemas/DataValueItemWithoutChanges'
    CrossLendingDataOverallResponse:
      type: object
      properties:
        totalDeposited:
          $ref: '#/components/schemas/DataValueItem'
        totalBorrowed:
          $ref: '#/components/schemas/DataValueItem'
        volumeDeposited:
          $ref: '#/components/schemas/DataValueItem'
        volumeWithdrawn:
          $ref: '#/components/schemas/DataValueItem'
        volumeBorrowed:
          $ref: '#/components/schemas/DataValueItem'
        volumeRepaid:
          $ref: '#/components/schemas/DataValueItem'
        feesPaidTheoretically:
          $ref: '#/components/schemas/DataValueItem'
        dayData:
          type: array
          items:
            $ref: '#/components/schemas/CrossLendingDayData'
