export const ChainNames = {
  ethereum: 'ethereum',
  arbitrum: 'arbitrum',
  optimism: 'optimism',
  base: 'base',
  polygon: 'polygon',
  bnbchain: 'bnbchain',
  fantom: 'fantom',
  avalanche: 'avalanche',
  gnosis: 'gnosis',
  metis: 'metis',
  scroll: 'scroll',
  blast: 'blast',
  linea: 'linea',
  zksync: 'zksync',
};

export const ProtocolNames = {
  aave: 'aave',
  aavev2: 'aavev2',
  aavev3: 'aavev3',
  abracadabra: 'abracadabra',
  compound: 'compound',
  compoundv3: 'compoundv3',
  ironbank: 'ironbank',
  kinza: 'kinza',
  kyberswap: 'kyberswap',
  liquity: 'liquity',
  maker: 'maker',
  mendi: 'mendi',
  orbit: 'orbit',
  pac: 'pac',
  pancake: 'pancake',
  pancakev3: 'pancakev3',
  radiant: 'radiant',
  seamless: 'seamless',
  sonne: 'sonne',
  spark: 'spark',
  spooky: 'spooky',
  sushi: 'sushi',
  sushiv3: 'sushiv3',
  uniswap: 'uniswap',
  uniswapv2: 'uniswapv2',
  uniswapv3: 'uniswapv3',
  venus: 'venus',
  zerolend: 'zerolend',
};
