import { OracleConfig } from '../../types/configs';
import { AddressE, AddressF, AddressZero } from '../constants';
import ArbitrumTokenList from '../tokenlists/arbitrum.json';
import AvalancheTokenList from '../tokenlists/avalanche.json';
import BaseTokenList from '../tokenlists/base.json';
import BnbchainTokenList from '../tokenlists/bnbchain.json';
import EthereumTokenList from '../tokenlists/ethereum.json';
import FantomTokenList from '../tokenlists/fantom.json';
import OptimismTokenList from '../tokenlists/optimism.json';
import PolygonTokenList from '../tokenlists/polygon.json';
import { OracleSourceConfigs } from './sources';

// chain => tokenAddress => config
export const OracleConfigs: { [key: string]: { [key: string]: OracleConfig } } = {
  // tokens on Ethereum
  ethereum: {
    [AddressZero]: OracleSourceConfigs.ETH,
    [AddressE]: OracleSourceConfigs.ETH,
    [AddressF]: OracleSourceConfigs.ETH,
    [EthereumTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [EthereumTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [EthereumTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [EthereumTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [EthereumTokenList.TUSD.address]: OracleSourceConfigs.TUSD,
    [EthereumTokenList.sUSD.address]: OracleSourceConfigs.sUSD,
    [EthereumTokenList.LEND.address]: OracleSourceConfigs.LEND,
    [EthereumTokenList.BAT.address]: OracleSourceConfigs.BAT,
    [EthereumTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [EthereumTokenList.KNC.address]: OracleSourceConfigs.KNC,
    '0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202': OracleSourceConfigs.KNC,
    '0xd5147bc8e386d91cc5dbe72099dac6c9b99276f5': OracleSourceConfigs.FIL,
    [EthereumTokenList.REP.address]: OracleSourceConfigs.REP,
    [EthereumTokenList.REPv2.address]: OracleSourceConfigs.REP,
    [EthereumTokenList.MKR.address]: OracleSourceConfigs.MKR,
    [EthereumTokenList.MANA.address]: OracleSourceConfigs.MANA,
    [EthereumTokenList.ZRX.address]: OracleSourceConfigs.ZRX,
    [EthereumTokenList.SNX.address]: OracleSourceConfigs.SNX,
    [EthereumTokenList.WBTC.address]: OracleSourceConfigs.WBTC,
    [EthereumTokenList.BUSD.address]: OracleSourceConfigs.BUSD,
    [EthereumTokenList.ENJ.address]: OracleSourceConfigs.ENJ,
    [EthereumTokenList.REN.address]: OracleSourceConfigs.REN,
    [EthereumTokenList.YFI.address]: OracleSourceConfigs.YFI,
    [EthereumTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [EthereumTokenList.UNI.address]: OracleSourceConfigs.UNI,
    [EthereumTokenList.CRV.address]: OracleSourceConfigs.CRV,
    [EthereumTokenList.BAL.address]: OracleSourceConfigs.BAL,
    [EthereumTokenList.xSUSHI.address]: OracleSourceConfigs.xSUSHI,
    [EthereumTokenList.GUSD.address]: OracleSourceConfigs.GUSD,
    [EthereumTokenList.RAI.address]: OracleSourceConfigs.RAI,
    [EthereumTokenList.USDP.address]: OracleSourceConfigs.USDP,
    [EthereumTokenList.PAX.address]: OracleSourceConfigs.USDP,
    '0x8e870d67f660d95d5be530380d0ec0bd388289e1': OracleSourceConfigs.USDP,
    [EthereumTokenList.AMPL.address]: OracleSourceConfigs.AMPL,
    [EthereumTokenList.DPI.address]: OracleSourceConfigs.DPI,
    [EthereumTokenList.FRAX.address]: OracleSourceConfigs.FRAX,
    [EthereumTokenList.FEI.address]: OracleSourceConfigs.FEI,
    [EthereumTokenList.stETH.address]: OracleSourceConfigs.stETH,
    [EthereumTokenList.wstETH.address]: OracleSourceConfigs.wstETH,
    [EthereumTokenList.ENS.address]: OracleSourceConfigs.ENS,
    [EthereumTokenList.UST.address]: OracleSourceConfigs.UST,
    [EthereumTokenList['1INCH'].address]: OracleSourceConfigs['1INCH'],
    [EthereumTokenList.CVX.address]: OracleSourceConfigs.CVX,
    [EthereumTokenList.LUSD.address]: OracleSourceConfigs.LUSD,
    [EthereumTokenList.SUSHI.address]: OracleSourceConfigs.SUSHI,
    [EthereumTokenList.cbETH.address]: OracleSourceConfigs.cbETH,
    [EthereumTokenList.rETH.address]: OracleSourceConfigs.rETH,
    [EthereumTokenList.LDO.address]: OracleSourceConfigs.LDO,
    [EthereumTokenList.GHO.address]: OracleSourceConfigs.GHO,
    [EthereumTokenList.RPL.address]: OracleSourceConfigs.RPL,
    [EthereumTokenList.sDAI.address]: OracleSourceConfigs.sDAI,
    [EthereumTokenList.STG.address]: OracleSourceConfigs.STG,
    [EthereumTokenList.COMP.address]: OracleSourceConfigs.COMP,
    [EthereumTokenList.SAI.address]: OracleSourceConfigs.SAI,
    [EthereumTokenList.EURS.address]: OracleSourceConfigs.EURS,
    [EthereumTokenList.sEUR.address]: OracleSourceConfigs.EURS,
    [EthereumTokenList.MIM.address]: OracleSourceConfigs.MIM,
    [EthereumTokenList.FXS.address]: OracleSourceConfigs.FXS,
    [EthereumTokenList.crvUSD.address]: OracleSourceConfigs.crvUSD,
    [EthereumTokenList.vBTC.address]: OracleSourceConfigs.vBTC,
    [EthereumTokenList.CREAM.address]: OracleSourceConfigs.CREAM,
    [EthereumTokenList.BAC.address]: OracleSourceConfigs.BAC,
    [EthereumTokenList.ALPHA.address]: OracleSourceConfigs.ALPHA,
    [EthereumTokenList.NFTX.address]: OracleSourceConfigs.NFTX,
    [EthereumTokenList.STETH.address]: OracleSourceConfigs.STETH,
    [EthereumTokenList.pONT.address]: OracleSourceConfigs.pONT,
    [EthereumTokenList.PENDLE.address]: OracleSourceConfigs.PENDLE,
    [EthereumTokenList.DOLA.address]: OracleSourceConfigs.DOLA,
    [EthereumTokenList.OHMv1.address]: OracleSourceConfigs.OHMv1,
    [EthereumTokenList.OHM.address]: OracleSourceConfigs.OHM,
    [EthereumTokenList.agEUR.address]: OracleSourceConfigs.agEUR,
  },

  // tokens on Arbitrum One
  arbitrum: {
    [AddressZero]: OracleSourceConfigs.ETH,
    [AddressE]: OracleSourceConfigs.ETH,
    [AddressF]: OracleSourceConfigs.ETH,
    [ArbitrumTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [ArbitrumTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [ArbitrumTokenList['USDC.e'].address]: OracleSourceConfigs.USDC,
    [ArbitrumTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [ArbitrumTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [ArbitrumTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [ArbitrumTokenList.WBTC.address]: OracleSourceConfigs.WBTC,
    [ArbitrumTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [ArbitrumTokenList.EURS.address]: OracleSourceConfigs.EURS,
    [ArbitrumTokenList.wstETH.address]: OracleSourceConfigs.wstETH,
    [ArbitrumTokenList.LUSD.address]: OracleSourceConfigs.LUSD,
    [ArbitrumTokenList.MAI.address]: OracleSourceConfigs.miMATIC,
    [ArbitrumTokenList.rETH.address]: OracleSourceConfigs.rETH,
    [ArbitrumTokenList.FRAX.address]: OracleSourceConfigs.FRAX,
    [ArbitrumTokenList.ARB.address]: OracleSourceConfigs.ARB,
  },

  // tokens on Optimism
  optimism: {
    [AddressZero]: OracleSourceConfigs.ETH,
    [AddressE]: OracleSourceConfigs.ETH,
    [AddressF]: OracleSourceConfigs.ETH,
    [OptimismTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [OptimismTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [OptimismTokenList['USDC.e'].address]: OracleSourceConfigs.USDC,
    [OptimismTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [OptimismTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [OptimismTokenList.WBTC.address]: OracleSourceConfigs.WBTC,
    [OptimismTokenList.OP.address]: OracleSourceConfigs.OP,
    [OptimismTokenList.SNX.address]: OracleSourceConfigs.SNX,
    [OptimismTokenList.sUSD.address]: OracleSourceConfigs.sUSD,
    [OptimismTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [OptimismTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [OptimismTokenList.wstETH.address]: OracleSourceConfigs.wstETH,
    [OptimismTokenList.LUSD.address]: OracleSourceConfigs.LUSD,
    [OptimismTokenList.MAI.address]: OracleSourceConfigs.miMATIC,
    [OptimismTokenList.rETH.address]: OracleSourceConfigs.rETH,
  },

  // tokens on Base
  base: {
    [AddressZero]: OracleSourceConfigs.ETH,
    [AddressE]: OracleSourceConfigs.ETH,
    [AddressF]: OracleSourceConfigs.ETH,
    [BaseTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [BaseTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [BaseTokenList.USDbC.address]: OracleSourceConfigs.USDC,
    [BaseTokenList.cbETH.address]: OracleSourceConfigs.cbETH,
    [BaseTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [BaseTokenList.wstETH.address]: OracleSourceConfigs.wstETH,
  },

  // tokens on Polygon
  polygon: {
    [AddressZero]: OracleSourceConfigs.MATIC,
    [AddressE]: OracleSourceConfigs.MATIC,
    [AddressF]: OracleSourceConfigs.MATIC,
    [PolygonTokenList.WMATIC.address]: OracleSourceConfigs.MATIC,
    [PolygonTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [PolygonTokenList['USDC.e'].address]: OracleSourceConfigs.USDC,
    [PolygonTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [PolygonTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [PolygonTokenList.WBTC.address]: OracleSourceConfigs.WBTC,
    [PolygonTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [PolygonTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [PolygonTokenList.GHST.address]: OracleSourceConfigs.GHST,
    [PolygonTokenList.BAL.address]: OracleSourceConfigs.BAL,
    [PolygonTokenList.DPI.address]: OracleSourceConfigs.DPI,
    [PolygonTokenList.CRV.address]: OracleSourceConfigs.CRV,
    [PolygonTokenList.SUSHI.address]: OracleSourceConfigs.SUSHI,
    [PolygonTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [PolygonTokenList.EURS.address]: OracleSourceConfigs.EURS,
    [PolygonTokenList.jEUR.address]: OracleSourceConfigs.jEUR,
    [PolygonTokenList.agEUR.address]: OracleSourceConfigs.agEUR,
    [PolygonTokenList.miMATIC.address]: OracleSourceConfigs.miMATIC,
    [PolygonTokenList.stMATIC.address]: OracleSourceConfigs.stMATIC,
    [PolygonTokenList.MaticX.address]: OracleSourceConfigs.MaticX,
    [PolygonTokenList.wstETH.address]: OracleSourceConfigs.wstETH,
    [PolygonTokenList.SD.address]: OracleSourceConfigs.SD,
    [PolygonTokenList.LDO.address]: OracleSourceConfigs.LDO,
  },

  // tokens on Bnbchain
  bnbchain: {
    [AddressZero]: OracleSourceConfigs.BNB,
    [AddressE]: OracleSourceConfigs.BNB,
    [AddressF]: OracleSourceConfigs.BNB,
    [BnbchainTokenList.WBNB.address]: OracleSourceConfigs.BNB,
    [BnbchainTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [BnbchainTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [BnbchainTokenList.ETH.address]: OracleSourceConfigs.ETH,
    [BnbchainTokenList.BTCB.address]: OracleSourceConfigs.WBTC,
    [BnbchainTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [BnbchainTokenList.ADA.address]: OracleSourceConfigs.ADA,
    [BnbchainTokenList.BCH.address]: OracleSourceConfigs.BCH,
    [BnbchainTokenList.BETH.address]: OracleSourceConfigs.BETH,
    [BnbchainTokenList.BUSD.address]: OracleSourceConfigs.BUSD,
    [BnbchainTokenList.CAKE.address]: OracleSourceConfigs.CAKE,
    [BnbchainTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [BnbchainTokenList.DOGE.address]: OracleSourceConfigs.DOGE,
    [BnbchainTokenList.DOT.address]: OracleSourceConfigs.DOT,
    [BnbchainTokenList.FIL.address]: OracleSourceConfigs.FIL,
    [BnbchainTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [BnbchainTokenList.LTC.address]: OracleSourceConfigs.LTC,
    [BnbchainTokenList.MATIC.address]: OracleSourceConfigs.MATIC,
    [BnbchainTokenList.SXP.address]: OracleSourceConfigs.SXP,
    [BnbchainTokenList.TRX.address]: OracleSourceConfigs.TRX,
    [BnbchainTokenList.TRXv2.address]: OracleSourceConfigs.TRX,
    [BnbchainTokenList.TUSD.address]: OracleSourceConfigs.TUSD,
    [BnbchainTokenList.TUSDv2.address]: OracleSourceConfigs.TUSD,
    [BnbchainTokenList.UNI.address]: OracleSourceConfigs.UNI,
    [BnbchainTokenList.UST.address]: OracleSourceConfigs.UST,
    [BnbchainTokenList.wBETH.address]: OracleSourceConfigs.wBETH,
    [BnbchainTokenList.USDD.address]: OracleSourceConfigs.USDD,
    [BnbchainTokenList.WIN.address]: OracleSourceConfigs.WIN,
    [BnbchainTokenList.BTT.address]: OracleSourceConfigs.BTT,
    [BnbchainTokenList.SnBNB.address]: OracleSourceConfigs.SnBNB,
    [BnbchainTokenList.stkBNB.address]: OracleSourceConfigs.stkBNB,
    [BnbchainTokenList.BNBx.address]: OracleSourceConfigs.BNBx,
    [BnbchainTokenList.ankrBNB.address]: OracleSourceConfigs.ankrBNB,
    [BnbchainTokenList.LUNA.address]: OracleSourceConfigs.LUNA,
    [BnbchainTokenList.XRP.address]: OracleSourceConfigs.XRP,
    [BnbchainTokenList.XVS.address]: OracleSourceConfigs.XVS,
    [BnbchainTokenList.HAY.address]: OracleSourceConfigs.HAY,
    [BnbchainTokenList.agEUR.address]: OracleSourceConfigs.agEUR,
    [BnbchainTokenList.BSW.address]: OracleSourceConfigs.BSW,
    [BnbchainTokenList.ALPACA.address]: OracleSourceConfigs.ALPACA,
    [BnbchainTokenList.ANKR.address]: OracleSourceConfigs.ANKR,
    [BnbchainTokenList.RACA.address]: OracleSourceConfigs.RACA,
    [BnbchainTokenList.TWT.address]: OracleSourceConfigs.TWT,
    [BnbchainTokenList.FLOKI.address]: OracleSourceConfigs.FLOKI,
  },

  // tokens on Avalanche C-Chain
  avalanche: {
    [AddressZero]: OracleSourceConfigs.AVAX,
    [AddressE]: OracleSourceConfigs.AVAX,
    [AddressF]: OracleSourceConfigs.AVAX,
    [AvalancheTokenList.WAVAX.address]: OracleSourceConfigs.AVAX,
    [AvalancheTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [AvalancheTokenList['USDC.e'].address]: OracleSourceConfigs.USDC,
    [AvalancheTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [AvalancheTokenList['USDT.e'].address]: OracleSourceConfigs.USDT,
    [AvalancheTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [AvalancheTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [AvalancheTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [AvalancheTokenList.WBTC.address]: OracleSourceConfigs.WBTC,
    [AvalancheTokenList['BTC.b'].address]: OracleSourceConfigs.WBTC,
    [AvalancheTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [AvalancheTokenList.sAVAX.address]: OracleSourceConfigs.sAVAX,
    [AvalancheTokenList.FRAX.address]: OracleSourceConfigs.FRAX,
    [AvalancheTokenList.MAI.address]: OracleSourceConfigs.miMATIC,
    [AvalancheTokenList.MIM.address]: OracleSourceConfigs.MIM,
    [AvalancheTokenList.ALPHA.address]: OracleSourceConfigs.ALPHA,
    [AvalancheTokenList.BUSD.address]: OracleSourceConfigs.BUSD,
    [AvalancheTokenList.QI.address]: OracleSourceConfigs.QI,
  },

  // tokens on Fantom
  fantom: {
    [AddressZero]: OracleSourceConfigs.FTM,
    [AddressE]: OracleSourceConfigs.FTM,
    [AddressF]: OracleSourceConfigs.FTM,
    [FantomTokenList.WFTM.address]: OracleSourceConfigs.FTM,
    [FantomTokenList.USDC.address]: OracleSourceConfigs.USDC,
    [FantomTokenList.lzUSDC.address]: OracleSourceConfigs.USDC,
    [FantomTokenList.anyUSDC.address]: OracleSourceConfigs.USDC,
    [FantomTokenList.fUSDT.address]: OracleSourceConfigs.USDT,
    [FantomTokenList.USDT.address]: OracleSourceConfigs.USDT,
    [FantomTokenList.DAI.address]: OracleSourceConfigs.DAI,
    [FantomTokenList.WETH.address]: OracleSourceConfigs.ETH,
    [FantomTokenList.anyWETH.address]: OracleSourceConfigs.ETH,
    [FantomTokenList.WBTC.address]: OracleSourceConfigs.WBTC,
    [FantomTokenList.anyWBTC.address]: OracleSourceConfigs.WBTC,
    [FantomTokenList.LINK.address]: OracleSourceConfigs.LINK,
    [FantomTokenList.AAVE.address]: OracleSourceConfigs.AAVE,
    [FantomTokenList.CRV.address]: OracleSourceConfigs.CRV,
    [FantomTokenList.SUSHI.address]: OracleSourceConfigs.SUSHI,
    [FantomTokenList.anyYFI.address]: OracleSourceConfigs.YFI,
    [FantomTokenList.SNX.address]: OracleSourceConfigs.SNX,
    [FantomTokenList.MIM.address]: OracleSourceConfigs.MIM,
    [FantomTokenList.FRAX.address]: OracleSourceConfigs.FRAX,
    [FantomTokenList.TUSD.address]: OracleSourceConfigs.TUSD,
    '0xe2d27f06f63d98b8e11b38b5b08a75d0c8dd62b9': OracleSourceConfigs.UST,
  },
};
